/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author satya
 */
public class ViewAllRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllRecord
     */
     DefaultTableModel model;
    public ViewAllRecord() {
        initComponents();
        setIssueBookDetailstoTable();
    }
    //to set the book details into the table
    
        public void setIssueBookDetailstoTable(){
            
            try {
                Connection con = dbconnection.getConnection();
                Statement st = con.createStatement();
                ResultSet rs= st.executeQuery("select * from issue_book_detail;");
                
                while(rs.next()){
                    
                    String id =rs.getString("id");
                    
                    String bookname =rs.getString("book_name");
                    String studentname =rs.getString("student_name");
                    String issueDate =rs.getString("issue_date");
                    String dueDate =rs.getString("due_date");
                    String status =rs.getString("stutus");
                    
                    Object[] obj = { id,bookname,studentname,issueDate,dueDate,status };
                    model =(DefaultTableModel) tbl_bookdeatals.getModel();
                    model.addRow(obj);
                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
         //clear table 
        public  void clearTable(){
            
            DefaultTableModel model= (DefaultTableModel)tbl_bookdeatals.getModel();
            model.setRowCount(0);
        }
        //to fetch the record  using date fields
        
        public  void search(){
            
            Date uFromDate = date_fromDate.getDatoFecha();
            Date uToDate = date_todate.getDatoFecha();
            
            long l1 = uFromDate.getTime();
            long l2 = uToDate.getTime();
            
            java.sql.Date fromDate = new java.sql.Date(l1);
            java.sql.Date toDate = new java.sql.Date(l2);
            
            try {
                Connection con = dbconnection.getConnection();
                String sql = "select * from issue_book_detail where issue_date BETWEEN ? and ?";
                PreparedStatement pst =con.prepareStatement(sql);
                pst.setDate(1, fromDate);
                pst.setDate(2, fromDate);
                ResultSet rs = pst.executeQuery();
                
                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "No Record Found");
                    
                }else{
                    while(rs.next()){
                    String id =rs.getString("id");
                    
                    String bookname =rs.getString("book_name");
                    String studentname =rs.getString("student_name");
                    String issueDate =rs.getString("issue_date");
                    String dueDate =rs.getString("due_date");
                    String status =rs.getString("stutus");
                    
                    Object[] obj = { id,bookname,studentname,issueDate,dueDate,status };
                    model =(DefaultTableModel) tbl_bookdeatals.getModel();
                    model.addRow(obj);
                }
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        date_todate = new rojeru_san.componentes.RSDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        date_fromDate = new rojeru_san.componentes.RSDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        panel_tbl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bookdeatals = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("View All Record");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, 360, 5));

        date_todate.setBackground(new java.awt.Color(255, 1, 51));
        date_todate.setForeground(new java.awt.Color(255, 255, 255));
        date_todate.setColorBackground(new java.awt.Color(255, 1, 51));
        date_todate.setColorForeground(new java.awt.Color(255, 1, 51));
        date_todate.setFuente(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        date_todate.setPlaceholder("Select  Due date");
        jPanel1.add(date_todate, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 370, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DueDate :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Issue Date :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        date_fromDate.setBackground(new java.awt.Color(255, 1, 51));
        date_fromDate.setForeground(new java.awt.Color(255, 255, 255));
        date_fromDate.setColorBackground(new java.awt.Color(255, 1, 51));
        date_fromDate.setColorForeground(new java.awt.Color(255, 1, 51));
        date_fromDate.setFuente(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        date_fromDate.setPlaceholder("Select Issue date");
        jPanel1.add(date_fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 370, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText("Back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle2.setText("Search");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 180, 130, 60));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle3.setText("ALL");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 180, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 280));

        panel_tbl.setBackground(new java.awt.Color(255, 255, 255));
        panel_tbl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_bookdeatals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Boook Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_bookdeatals.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_bookdeatals.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_bookdeatals.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_bookdeatals.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_bookdeatals.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        tbl_bookdeatals.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbl_bookdeatals.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_bookdeatals.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_bookdeatals.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_bookdeatals.setRowHeight(40);
        tbl_bookdeatals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bookdeatalsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_bookdeatals);

        panel_tbl.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 1240, 260));

        getContentPane().add(panel_tbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1480, 580));

        setSize(new java.awt.Dimension(1481, 857));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_bookdeatalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bookdeatalsMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_tbl_bookdeatalsMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        HomePage home =new HomePage();
        home.setVisible(true);
        dispose();

    }//GEN-LAST:event_jPanel2MouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        clearTable();
        search();
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
       clearTable();
       setIssueBookDetailstoTable();
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser date_fromDate;
    private rojeru_san.componentes.RSDateChooser date_todate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_tbl;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojerusan.RSTableMetro tbl_bookdeatals;
    // End of variables declaration//GEN-END:variables
}
